name: Generate Doxygen documentation

on:
  schedule:
  - cron: 0 1 * * *
  pull_request:
    branches:
    - sycl
    paths:
    - '.github/workflows/sycl-docs.yml'
    - 'clang/docs/**'
    - 'sycl/doc/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'uditagarwal97/llvm'
    steps:
    - uses: actions/checkout@v4
      with:
        path: repo
    - name: Install deps
      run: |
        sudo apt-get install -y doxygen graphviz ssh ninja-build libhwloc-dev
        sudo pip3 install -r repo/llvm/docs/requirements.txt
    - name: Build Docs
      run: |
        mkdir -p $GITHUB_WORKSPACE/build
        cd $GITHUB_WORKSPACE/build
        python $GITHUB_WORKSPACE/repo/buildbot/configure.py -w $GITHUB_WORKSPACE \
        -s $GITHUB_WORKSPACE/repo -o $GITHUB_WORKSPACE/build -t Release --docs
        cmake --build . --target docs-sycl-html
        cmake --build . --target docs-clang-html
        cd $GITHUB_WORKSPACE/docs
        yes | \cp -rf $GITHUB_WORKSPACE/build/tools/sycl/doc/html/* .
        mv $GITHUB_WORKSPACE/build/tools/clang/docs/html clang/
        touch .nojekyll
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: $GITHUB_WORKSPACE/docs
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

