name: Generate Doxygen documentation

on:
  schedule:
  - cron: 0 1 * * *
  pull_request:
    branches:
    - sycl
    paths:
    - '.github/workflows/sycl-docs.yml'
    - 'clang/docs/**'
    - 'sycl/doc/**'

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'uditagarwal97/llvm'
    steps:
    - uses: actions/checkout@v4
      with:
        path: repo
    - name: Install deps
      run: |
        sudo apt-get install -y doxygen graphviz ssh ninja-build libhwloc-dev
        sudo pip3 install -r repo/llvm/docs/requirements.txt
    - name: Build Docs
      run: |
        mkdir -p $GITHUB_WORKSPACE/build
        cd $GITHUB_WORKSPACE/build
        python $GITHUB_WORKSPACE/repo/buildbot/configure.py -w $GITHUB_WORKSPACE \
        -s $GITHUB_WORKSPACE/repo -o $GITHUB_WORKSPACE/build -t Release --docs
        cmake --build . --target docs-sycl-html
        cmake --build . --target docs-clang-html
        ls
        pwd

